name: Build doudizhu_endgame

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: change directory doudizhu
      run: |
        cd doudizhu

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake .
      working-directory: doudizhu  # 指定工作目录为包含 CMakeLists.txt 的 doudizhu 文件夹
    
    - name: Build project
      run: make
      working-directory: /home/runner/work/doudizhu_endgame/doudizhu_endgame/doudizhu  # 指定正确的构建文件所在的目录

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: /home/runner/work/doudizhu_endgame/doudizhu_endgame/doudizhu  # 指定要存档的路径
