name: Build doudizhu_endgame

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone doudizhu_endgame
      run: |
        cd doudizhu

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake .
      working-directory: doudizhu  # 指定工作目录为源代码目录


    - name: Build project
      run: make
      working-directory: doudizhu/build  # 指定工作目录为 build
