name: Build doudizhu_endgame

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone doudizhu_endgame
      run: |
        cd doudizhu_endgame

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake ..  # 注意这里的路径，因为我们已经在doudizhu_endgame目录下

    - name: Build project
      run: make
      working-directory: doudizhu_endgame/build  # 指定工作目录为 build
