name: Build doudizhu_endgame

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clean up build directory
      run: rm -rf /home/runner/work/doudizhu_endgame/build

    - name: List all files and directories001
      run: ls -R /home/runner/work/doudizhu_endgame

    - name: change directory doudizhu_endgame
      run: |
        cd doudizhu_endgame/doudizhu

    - name: change directory doudizhu
      run: |
        cd doudizhu

    - name: Create build directory
      run: mkdir build

    - name: change directory doudizhu
      run: |
        cd build
      
    - name: Configure CMake
      run: cmake ..
      working-directory: doudizhu  # 指定工作目录为包含 CMakeLists.txt 的 doudizhu 文件夹

    - name: Debug CMake
      run: cmake .. --debug-output
      working-directory: doudizhu
    
   # - name: Build project
   #   run: make
   #   working-directory: /home/runner/work/doudizhu_endgame/doudizhu_endgame/doudizhu  # 指定正确的构建文件所在的目录

    - name: Build project
      run: make VERBOSE=1
      working-directory: /home/runner/work/doudizhu_endgame/doudizhu_endgame/doudizhu
    
    - name: List all files and directories
      run: ls -R /home/runner/work/doudizhu_endgame

    - name: Find and archive executable
      run: find /home/runner/work/doudizhu_endgame -type f -executable -exec mv {} /home/runner/work/doudizhu_endgame/doudizhu \;
      working-directory: /home/runner/work/doudizhu_endgame

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: /home/runner/work/doudizhu_endgame/doudizhu_endgame # 指定要存档的路径
